version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    command: -p 5433
    expose:
      - 5433
    env_file:
      - cafe_dr/.env-docker

  app:
    build:
      context: .
    env_file:
      - cafe_dr/.env-docker
    container_name: app
    restart: always
    ports:
      - "8000:8080"
    depends_on:
      - db
