# Generated by Django 5.0.1 on 2024-01-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishrecipeorm",
            name="dish_recipe",
            field=models.TextField(blank=True, default=None),
        ),
    ]
